x = input('Input a number greater than your second number ')
y = input('Input a number lower than your first number ')
print(type(x))
print(type(y))
add = x + y
print(add)
a = int(x)
b = int(y)
print(type(a))
print(type(b))
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a ** b)

